# Generated by Django 5.1.2 on 2024-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer')], default='farmer', max_length=10),
        ),
        migrations.AddField(
            model_name='vet',
            name='role',
            field=models.CharField(choices=[('vet', 'Vet')], default='vet', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
