# Generated by Django 5.1.2 on 2024-10-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_farmer_role_vet_role_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='role',
        ),
    ]
