# Generated by Django 5.1.1 on 2025-09-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_vet_latitude_vet_longitude_vetrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='vet_requests/'),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='signs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vet_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
