# Generated by Django 5.1.2 on 2024-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_vet_latitude_remove_vet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
