# Generated by Django 5.1.1 on 2025-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_vetrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
