# Generated by Django 5.1.1 on 2025-09-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_vetrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetrequest',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vet_requests', to='profiles.vet'),
        ),
    ]
