# Generated by Django 5.1.3 on 2024-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_vet_is_available_vet_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
