# Generated by Django 5.1.1 on 2024-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_farmer_farm_location_farmer_first_name_farmer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
