# Generated by Django 5.1.1 on 2024-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_farmer_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(choices=[('Campaign', 'Campaign'), ('Referral', 'Referral'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
