# Generated by Django 5.1.1 on 2024-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_lead_email_alter_lead_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Follow-up', 'Follow-up'), ('Interested', 'Interested'), ('Lost', 'Lost')], default='New', max_length=50),
        ),
    ]
