# Generated by Django 5.1.1 on 2024-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referral_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Campaign', 'Campaign'), ('Referral', 'Referral'), ('Other', 'Other')], default='Campaign', max_length=100),
        ),
    ]
