# Generated by Django 5.1.1 on 2024-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_lead_referral_name_lead_referral_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
