# Generated by Django 5.1.1 on 2025-02-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_amount_remove_invoice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank='True', max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null='True'),
            preserve_default='True',
        ),
    ]
