# Generated by Django 5.1.1 on 2025-02-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('assigned_worker', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='FeedManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_management', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_cost_per_month', models.FloatField()),
                ('vet_expenses', models.FloatField()),
                ('breeding_costs', models.FloatField()),
                ('revenue_from_milk', models.FloatField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_details', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='LactationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lactation_number', models.IntegerField()),
                ('days_in_milk', models.IntegerField()),
                ('is_milking', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lactation_status', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='LifetimeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_milk', models.FloatField()),
                ('avg_yield', models.FloatField()),
                ('calves', models.IntegerField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_stats', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milk_yield', models.FloatField()),
                ('feed_consumption', models.FloatField()),
                ('scc', models.IntegerField()),
                ('fat_percentage', models.FloatField()),
                ('protein_percentage', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ReproductiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_history', to='animals.animal')),
            ],
        ),
    ]
