# Generated by Django 5.1.1 on 2024-10-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('breed', models.CharField(max_length=100)),
                ('milk_production', models.FloatField()),
            ],
            bases=('animals.animal',),
        ),
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('meat_yield', models.FloatField()),
            ],
            bases=('animals.animal',),
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('wool_yield', models.FloatField()),
            ],
            bases=('animals.animal',),
        ),
    ]
