# Generated by Django 5.1.2 on 2024-10-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_cow_goat_sheep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy_Cow',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('breed', models.CharField(max_length=100)),
                ('milk_production', models.FloatField()),
            ],
            bases=('animals.animal',),
        ),
        migrations.RenameModel(
            old_name='Cow',
            new_name='Beef_Cow',
        ),
        migrations.RenameField(
            model_name='beef_cow',
            old_name='milk_production',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheep',
            name='twin',
            field=models.BooleanField(default=False),
        ),
    ]
