# Generated by Django 5.1.1 on 2025-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='is_sick',
            field=models.BooleanField(default=False),
        ),
    ]
