# Generated by Django 5.1.2 on 2024-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_dairy_cow_rename_cow_beef_cow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/'),
        ),
    ]
