# Generated by Django 5.1.1 on 2025-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_healthrecord_is_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lactationstatus',
            name='days_in_milk',
            field=models.IntegerField(editable=False),
        ),
    ]
