# Generated by Django 5.1.1 on 2025-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_lactationstatus_expected_calving_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='clinical_signs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
