# Generated by Django 5.1.2 on 2024-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beef_cow',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beef_cow',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_cow',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_cow',
            name='milk_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='wool_yield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
