# Generated by Django 5.1.1 on 2025-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_healthrecord_clinical_signs_healthrecord_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='MORNING', max_length=10),
        ),
    ]
