# Generated by Django 5.1.1 on 2025-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_productiondata_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='cost',
            field=models.FloatField(default=0.0, help_text='Cost of this health record (e.g., vet fees, medication)'),
        ),
        migrations.AddField(
            model_name='reproductivehistory',
            name='cost',
            field=models.FloatField(default=0.0, help_text='Cost of this reproductive event (e.g., AI fees, breeding fees)'),
        ),
    ]
