# Generated by Django 5.1.1 on 2024-12-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animalgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
