# Generated by Django 5.1.1 on 2025-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_healthrecord_cost_reproductivehistory_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmanagement',
            name='cost_per_unit',
            field=models.FloatField(default=0.0, help_text='Cost per kg of feed'),
        ),
        migrations.AddField(
            model_name='feedmanagement',
            name='total_cost',
            field=models.FloatField(default=0.0, help_text='Total cost for this feed entry (quantity * cost_per_unit)'),
        ),
        migrations.AlterField(
            model_name='feedmanagement',
            name='quantity',
            field=models.FloatField(help_text='Quantity of feed in kg'),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='breeding_costs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='feed_cost_per_month',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='revenue_from_milk',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='vet_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
