# Generated by Django 5.1.1 on 2025-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_feedmanagement_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetails',
            name='breeding_costs',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='feed_cost_per_month',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='revenue_from_milk',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='vet_expenses',
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_breeding_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_feed_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_revenue_from_milk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_vet_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
