# Generated by Django 5.1.1 on 2024-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_animal_is_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
