# Generated by Django 5.1.1 on 2024-12-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='tag',
            new_name='farm_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='family_line',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='generation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
