# Generated by Django 5.1.1 on 2025-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_lactationperiod_delete_lactationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Calf (0-3 months)', 'Calf (0-3 months)'), ('Weaner Stage 1 (3-6 months)', 'Weaner Stage 1 (3-6 months)'), ('Weaner Stage 2 (6-9 months)', 'Weaner Stage 2 (6-9 months)'), ('Yearling (9-12 months)', 'Yearling (9-12 months)'), ('Bulling (12-15 months)', 'Bulling (12-15 months)'), ('In-Calf', 'In-Calf'), ('Steaming', 'Steaming'), ('Heifer', 'Heifer'), ('Early Lactating', 'Early Lactating'), ('Mid Lactating', 'Mid Lactating'), ('Late Lactating', 'Late Lactating'), ('Dry', 'Dry'), ('Bull', 'Bull')], max_length=50, unique=True)),
                ('feed_type', models.CharField(max_length=100)),
                ('daily_amount_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequency', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
