# Generated by Django 5.1.1 on 2025-03-27 08:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_delete_feedplan_alter_feedmanagement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='milk_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
