# Generated by Django 5.1.1 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_productiondata_milk_price_per_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='feed_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='protein_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='scc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
