# Generated by Django 5.1.1 on 2025-11-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_alter_productiondata_fat_percentage_and_more'),
    ]

    operations = [
    ]
