# Generated by Django 5.1.1 on 2025-11-03 07:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_enable_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
