# Generated by Django 5.1.1 on 2025-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('farm_code', models.CharField(max_length=50, unique=True)),
                ('initial_setup_fee', models.DecimalField(decimal_places=2, default=150000.0, max_digits=10)),
                ('downpayment', models.DecimalField(decimal_places=2, default=75000.0, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('recurring_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paybill_number', models.CharField(default='880100', max_length=50)),
                ('account_number', models.CharField(default='302301', max_length=50)),
                ('bank_account', models.CharField(default='1000614126', max_length=50)),
                ('due_date', models.IntegerField(default=5)),
                ('notice_period_months', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
