# Generated by Django 5.1.1 on 2025-02-28 17:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('wool', 'Wool')], max_length=20)),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='Morning', max_length=20)),
                ('date', models.DateField()),
                ('output', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='animals.animal')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('Tomatoes', 'Tomatoes'), ('Onions', 'Onions'), ('Cabbage', 'Cabbage'), ('Kales', 'Kales'), ('Milk', 'Milk'), ('Potatoes', 'Potatoes')], max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('last_updated', models.DateField(auto_now=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
