# Generated by Django 5.1.1 on 2024-12-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_beefmedicalrecord_dairymedicalrecord_and_more'),
        ('production', '0002_alter_production_farmer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='quantity',
            new_name='output',
        ),
        migrations.AddField(
            model_name='production',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='production',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='Morning', max_length=20),
        ),
    ]
