# Generated by Django 5.1.1 on 2024-11-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_ip', models.CharField(help_text='IP address of the camera', max_length=255)),
                ('username', models.CharField(help_text='Username for the camera', max_length=100)),
                ('password', models.CharField(help_text='Password for the camera', max_length=100)),
                ('rtsp_stream_url', models.CharField(blank=True, help_text='Generated RTSP stream URL', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
