# Generated by Django 5.1.1 on 2024-12-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_remove_camera_camera_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('rtsp_url', models.URLField()),
                ('janus_stream_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='camera.nvr')),
            ],
        ),
        migrations.CreateModel(
            name='JanusStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janus_room_id', models.PositiveIntegerField()),
                ('janus_server_url', models.URLField()),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janus_stream', to='camera.stream')),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
