# Generated by Django 5.1.1 on 2024-12-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_nvr_stream_janusstream_delete_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
