# Generated by Django 5.1.1 on 2024-12-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_price'),
        ('market', '0002_auction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='name',
        ),
        migrations.AddField(
            model_name='auction',
            name='animal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
        migrations.AddField(
            model_name='auction',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
