# Generated by Django 5.1.1 on 2024-12-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_delete_product_remove_auction_name_auction_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
