# Generated by Django 5.1.1 on 2024-12-04 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 9, 29, 6, 440589, tzinfo=datetime.timezone.utc)),
        ),
    ]
