# Generated by Django 5.1.1 on 2025-02-28 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 18, 6, 34, 446107, tzinfo=datetime.timezone.utc)),
        ),
    ]
