# Generated by Django 5.1.1 on 2025-02-28 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 18, 18, 47, 90991, tzinfo=datetime.timezone.utc)),
        ),
    ]
