# Generated by Django 5.1.1 on 2024-12-04 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 9, 30, 16, 353567, tzinfo=datetime.timezone.utc)),
        ),
    ]
