# Generated by Django 5.1.1 on 2025-03-01 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 21, 11, 45, 197111, tzinfo=datetime.timezone.utc)),
        ),
    ]
