# Generated by Django 5.1.1 on 2025-03-04 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 7, 27, 32, 507561, tzinfo=datetime.timezone.utc)),
        ),
    ]
