# Generated by Django 5.1.1 on 2024-12-16 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 13, 56, 9, 212829, tzinfo=datetime.timezone.utc)),
        ),
    ]
