# Generated by Django 5.1.1 on 2024-12-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 14, 3, 49, 558392, tzinfo=datetime.timezone.utc)),
        ),
    ]
