# Generated by Django 5.1.1 on 2025-03-04 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 9, 23, 48, 632355, tzinfo=datetime.timezone.utc)),
        ),
    ]
