# Generated by Django 5.1.1 on 2025-03-04 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 9, 25, 17, 102898, tzinfo=datetime.timezone.utc)),
        ),
    ]
