# Generated by Django 5.1.1 on 2024-12-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 15, 14, 55, 369947, tzinfo=datetime.timezone.utc)),
        ),
    ]
