# Generated by Django 5.1.1 on 2025-03-05 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 10, 37, 36, 22561, tzinfo=datetime.timezone.utc)),
        ),
    ]
