# Generated by Django 5.1.1 on 2025-03-05 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 12, 7, 51, 499091, tzinfo=datetime.timezone.utc)),
        ),
    ]
