# Generated by Django 5.1.1 on 2024-12-16 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 15, 16, 46, 379602, tzinfo=datetime.timezone.utc)),
        ),
    ]
