# Generated by Django 5.1.1 on 2024-12-17 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 7, 28, 35, 324476, tzinfo=datetime.timezone.utc)),
        ),
    ]
