# Generated by Django 5.1.1 on 2025-03-06 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 10, 36, 44, 485338, tzinfo=datetime.timezone.utc)),
        ),
    ]
