# Generated by Django 5.1.1 on 2024-12-17 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 9, 9, 33, 951414, tzinfo=datetime.timezone.utc)),
        ),
    ]
