# Generated by Django 5.1.1 on 2025-03-11 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 16, 59, 15, 606646, tzinfo=datetime.timezone.utc)),
        ),
    ]
