# Generated by Django 5.1.1 on 2025-03-11 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 20, 11, 59, 57442, tzinfo=datetime.timezone.utc)),
        ),
    ]
