# Generated by Django 5.1.1 on 2024-12-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 15, 1, 2, 934598, tzinfo=datetime.timezone.utc)),
        ),
    ]
