# Generated by Django 5.1.1 on 2025-03-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_passwordresettoken_expires_at'),
    ]

    operations = [
    ]
