# Generated by Django 5.1.1 on 2024-12-20 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 16, 25, 58, 573494, tzinfo=datetime.timezone.utc)),
        ),
    ]
