# Generated by Django 5.1.1 on 2025-03-12 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 9, 55, 56, 16209, tzinfo=datetime.timezone.utc)),
        ),
    ]
