# Generated by Django 5.1.1 on 2025-03-12 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 11, 40, 46, 441101, tzinfo=datetime.timezone.utc)),
        ),
    ]
