# Generated by Django 5.1.1 on 2024-12-21 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 9, 41, 26, 63274, tzinfo=datetime.timezone.utc)),
        ),
    ]
