# Generated by Django 5.1.1 on 2024-12-21 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 9, 44, 9, 382158, tzinfo=datetime.timezone.utc)),
        ),
    ]
