# Generated by Django 5.1.1 on 2025-03-12 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 14, 3, 58, 254736, tzinfo=datetime.timezone.utc)),
        ),
    ]
