# Generated by Django 5.1.1 on 2024-12-23 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 8, 33, 41, 500991, tzinfo=datetime.timezone.utc)),
        ),
    ]
