# Generated by Django 5.1.1 on 2025-03-13 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 49, 41, 642511, tzinfo=datetime.timezone.utc)),
        ),
    ]
