# Generated by Django 5.1.1 on 2024-12-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 9, 16, 32, 451209, tzinfo=datetime.timezone.utc)),
        ),
    ]
