# Generated by Django 5.1.1 on 2025-03-24 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 10, 43, 23, 548256, tzinfo=datetime.timezone.utc)),
        ),
    ]
