# Generated by Django 5.1.1 on 2024-12-23 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 11, 15, 5, 664125, tzinfo=datetime.timezone.utc)),
        ),
    ]
