# Generated by Django 5.1.1 on 2024-12-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 13, 0, 10, 595748, tzinfo=datetime.timezone.utc)),
        ),
    ]
