# Generated by Django 5.1.1 on 2025-03-26 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 10, 57, 11, 583807, tzinfo=datetime.timezone.utc)),
        ),
    ]
