# Generated by Django 5.1.1 on 2024-12-25 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 10, 27, 35, 904441, tzinfo=datetime.timezone.utc)),
        ),
    ]
