# Generated by Django 5.1.1 on 2025-04-08 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 13, 30, 44, 839774, tzinfo=datetime.timezone.utc)),
        ),
    ]
