# Generated by Django 5.1.1 on 2025-03-26 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 16, 33, 59, 208855, tzinfo=datetime.timezone.utc)),
        ),
    ]
