# Generated by Django 5.1.1 on 2024-12-25 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 12, 21, 49, 699433, tzinfo=datetime.timezone.utc)),
        ),
    ]
