# Generated by Django 5.1.1 on 2025-03-27 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 8, 24, 40, 39458, tzinfo=datetime.timezone.utc)),
        ),
    ]
