# Generated by Django 5.1.1 on 2024-12-29 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 57, 19, 52251, tzinfo=datetime.timezone.utc)),
        ),
    ]
