# Generated by Django 5.1.1 on 2024-12-29 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 16, 5, 51, 337393, tzinfo=datetime.timezone.utc)),
        ),
    ]
