# Generated by Django 5.1.1 on 2025-02-03 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 14, 16, 56, 961060, tzinfo=datetime.timezone.utc)),
        ),
    ]
