# Generated by Django 5.1.1 on 2025-03-27 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 9, 45, 14, 578151, tzinfo=datetime.timezone.utc)),
        ),
    ]
