# Generated by Django 5.1.1 on 2025-03-27 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 13, 57, 10, 235997, tzinfo=datetime.timezone.utc)),
        ),
    ]
