# Generated by Django 5.1.1 on 2025-02-03 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 15, 52, 38, 288647, tzinfo=datetime.timezone.utc)),
        ),
    ]
