# Generated by Django 5.1.1 on 2025-03-31 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 11, 37, 48, 445101, tzinfo=datetime.timezone.utc)),
        ),
    ]
