# Generated by Django 5.1.1 on 2025-03-31 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 12, 10, 42, 758888, tzinfo=datetime.timezone.utc)),
        ),
    ]
