# Generated by Django 5.1.1 on 2025-02-05 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 1, 2, 44, 975723, tzinfo=datetime.timezone.utc)),
        ),
    ]
