# Generated by Django 5.1.1 on 2025-07-21 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 10, 36, 49, 558565, tzinfo=datetime.timezone.utc)),
        ),
    ]
