# Generated by Django 5.1.1 on 2025-04-01 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 9, 14, 11, 624826, tzinfo=datetime.timezone.utc)),
        ),
    ]
