# Generated by Django 5.1.1 on 2025-07-25 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 10, 20, 14, 613267, tzinfo=datetime.timezone.utc)),
        ),
    ]
