# Generated by Django 5.1.1 on 2025-08-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_passwordresettoken_expires_at'),
        ('accounts', '0052_alter_passwordresettoken_expires_at'),
    ]

    operations = [
    ]
