# Generated by Django 5.2.4 on 2025-07-31 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_merge_20250731_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 9, 22, 4, 182246, tzinfo=datetime.timezone.utc)),
        ),
    ]
