# Generated by Django 5.2.4 on 2025-07-31 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 9, 26, 38, 867196, tzinfo=datetime.timezone.utc)),
        ),
    ]
