# Generated by Django 5.2.4 on 2025-08-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_merge_20250827_1514'),
        ('accounts', '0055_alter_passwordresettoken_expires_at'),
    ]

    operations = [
    ]
