# Generated by Django 5.1.1 on 2025-09-08 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_merge_20250829_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 13, 58, 17, 382467, tzinfo=datetime.timezone.utc)),
        ),
    ]
