# Generated by Django 5.1.1 on 2025-09-08 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 14, 43, 41, 212667, tzinfo=datetime.timezone.utc)),
        ),
    ]
