# Generated by Django 5.1.1 on 2025-10-23 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_user_cover_image_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 6, 27, 6, 12640, tzinfo=datetime.timezone.utc)),
        ),
    ]
