# Generated by Django 5.1.1 on 2025-10-31 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 14, 29, 18, 458408, tzinfo=datetime.timezone.utc)),
        ),
    ]
