# Generated by Django 5.1.1 on 2025-11-03 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 7, 57, 5, 799168, tzinfo=datetime.timezone.utc)),
        ),
    ]
