# Generated by Django 5.1.1 on 2025-11-07 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 12, 54, 4, 130016, tzinfo=datetime.timezone.utc)),
        ),
    ]
