# Generated by Django 5.1.1 on 2025-11-12 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 12, 10, 31, 604899, tzinfo=datetime.timezone.utc)),
        ),
    ]
