# Generated by Django 5.1.1 on 2025-11-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 12, 53, 1, 592395, tzinfo=datetime.timezone.utc)),
        ),
    ]
