# Generated by Django 5.1.1 on 2025-11-13 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 10, 8, 58, 528897, tzinfo=datetime.timezone.utc)),
        ),
    ]
