# Generated by Django 5.1.1 on 2025-11-14 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 8, 26, 40, 612889, tzinfo=datetime.timezone.utc)),
        ),
    ]
