# Generated by Django 5.1.1 on 2025-11-17 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 8, 17, 31, 405931, tzinfo=datetime.timezone.utc)),
        ),
    ]
