# Generated by Django 5.1.1 on 2025-11-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drug_products/'),
        ),
    ]
