# Generated by Django 5.1.1 on 2025-02-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Needs Repair', 'Needs Repair')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machinery_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_machinery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='machinery.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Fuel', 'Fuel')], max_length=100)),
                ('threshold', models.FloatField()),
                ('notified', models.BooleanField(default=False)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='machinery.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='MachineryUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operator', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='machinery.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='machinery.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='machinery.machinery')),
            ],
        ),
    ]
