# Generated by Django 5.1.1 on 2025-07-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryVendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type_of_machine', models.CharField(choices=[('TRACTOR', 'Tractor'), ('HARVESTER', 'Harvester'), ('PLOUGH', 'Plough'), ('OTHER', 'Other')], max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
