# Generated by Django 5.1.1 on 2025-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_machineryvendorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineryvendorapplication',
            name='location',
        ),
        migrations.AddField(
            model_name='machineryvendorapplication',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineryvendorapplication',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
