# Generated by Django 5.1.1 on 2025-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_remove_machineryvendorapplication_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machineryvendorapplication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
