# Generated by Django 5.1.1 on 2025-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_machineryvendorapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryvendorapplication',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate charged per day in your local currency', max_digits=10),
        ),
    ]
