# Generated by Django 5.1.1 on 2025-07-18 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0007_machineryorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineryorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='land_size_acres',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='vendor_application',
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='machinery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_machinery', to='machinery.machineryvendorapplication'),
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_vendor', to='machinery.machineryvendorapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
    ]
