# Generated by Django 5.1.1 on 2025-07-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0010_alter_machineryorder_machinery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineryorder',
            name='machinery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_machinery', to='machinery.machinery'),
        ),
    ]
