# Generated by Django 5.1.1 on 2025-07-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0011_alter_machineryorder_machinery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineryorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='machineryorder',
            name='vendor_application',
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='land_size_acres',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='machinery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machineryvendorapplication'),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machineryorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_orders_as_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
