# Generated by Django 5.1.1 on 2025-03-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0005_farm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheepType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avg_wool_yield', models.FloatField(default=0.0)),
                ('avg_weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='farms.farm')),
                ('sheep_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheep', to='sheep_app.sheeptype')),
            ],
        ),
        migrations.CreateModel(
            name='SheepHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_sick', models.BooleanField(default=False)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='sheep_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='SheepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sheep_images/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sheep_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='SheepProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('wool_yield', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('shearing_date', models.DateField(blank=True, null=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='sheep_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='SheepReproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField()),
                ('partner_tag', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('offspring_count', models.PositiveIntegerField(default=0)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_records', to='sheep_app.sheep')),
            ],
        ),
    ]
