# Generated by Django 5.1.1 on 2025-03-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produce_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add to Plateau'), ('TRANSFER', 'Transfer to Outlet')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='inventory.outlet')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produce')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='inventory.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produce')),
            ],
            options={
                'unique_together': {('produce', 'outlet')},
            },
        ),
    ]
