# Generated by Django 5.1.1 on 2025-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
