
"""
Django settings for farm_management project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "95.179.165.24",
    "95.179.245.72",
    "api.agrieldo.com",
    "127.0.0.1",
    "192.168.100.4",
    "0.0.0.0",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",


     #rest apps
    'accounts',
    'billing',
    'messaging',
    'inventory',
    'AI_Chat',
    'merchandise',
    'market',
    'Subscriber',
    'store',
    'sheep_app',
    'team',
    'education',
    'tasks',
    'animals.apps.AnimalsConfig',
    'farms',
    'machinery',
    'contracts',
    'subscriptions', 
    'finances',
    'feed',
    'profiles',
    'production',
    'camera',
    'feed_store',
    'drug_store',
    'calendar_app',
    'rest_framework_gis',
    'channels',
    'django_celery_beat',  # Add this to your installed apps
    'orders',
    'fcm_django',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',
    'social_django',  # For social authentication
  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',


]

# settings.py
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_SECURE = False  # Set to True for production with HTTPS
CSRF_COOKIE_HTTPONLY = False

# Celcom SMS credentials
SMS_API_KEY = os.getenv("SMS_API_KEY")

SMS_PARTNER_ID = os.getenv("SMS_PARTNER_ID ")

SMS_SHORTCODE = os.getenv("SMS_SHORTCODE")



ROOT_URLCONF = 'farm_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add your template path here
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm_management.wsgi.application'

ASGI_APPLICATION = 'farm_management.asgi.application'

# Channel Layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Ensure Redis is running on this host/port
        },
    },
}
#install redis
#sudo apt update
#sudo apt install redis-server

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AIzaSyAUsPLSOA9ndp9LC4XYnVgN6Y9ykqGz22Q",  # Replace with your FCM server key from Firebase
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = [
    '*',
    "http://localhost:19000",     # React Native development server
    "http://192.168.100.4:8000",  # Local Django development server
    "http://localhost:3001",     # React Native development server
    "https://crm.agrieldo.com",
    "https://agrieldo.com",
    "https://api.agrieldo.com",  # ✅ Must be here, since it's where frontend is talking to the backend
    "https://www.agrieldo.com",
    "http://crm.agrieldo.com",
    "http://agrieldo.com",
    "http://192.168.100.4:3001",  # Local Django development server
    "http://192.168.100.4:8000",  # Local Django development server due to changes
    "http://95.179.245.72:8000",
    "http://localhost:3000",     # React Native development server
    "http://localhost:3002", 


]

CSRF_TRUSTED_ORIGINS = [
    "https://api.agrieldo.com",
    "https://www.agrieldo.com",
]


# Allow credentials (if using tokens/cookies)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Change this if you're using a different broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # You can change the backend as well
CELERY_TIMEZONE = 'Africa/Nairobi'  # Match Django's TIME_ZONE if changed
CELERY_ENABLE_UTC = False  # Enable UTC support


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '<your-google-client-id>'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '<your-google-client-secret>'

SOCIAL_AUTH_FACEBOOK_KEY = '<your-facebook-app-id>'
SOCIAL_AUTH_FACEBOOK_SECRET = '<your-facebook-app-secret>'

SOCIAL_AUTH_JSONFIELD_ENABLED = True  # For storing extra data from the social login response
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # Increase to 5MB or more as needed


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),  # Short access token lifetime
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # Very long refresh token lifetime
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Fixed line
}


# settings.py
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/var/www/agrieldo/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

MEDIA_ROOT = '/var/www/agrieldo/media'
MEDIA_URL = '/media/'



GOOGLE_SHEETS_CREDENTIALS_FILE = BASE_DIR / 'google_service_account.json'

# settings.py
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt4o-agrieldo")



MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")



