# Generated by Django 5.1.1 on 2025-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
        migrations.AddField(
            model_name='feed',
            name='price_per_kg',
            field=models.FloatField(default=0.0, help_text='Cost per kg'),
        ),
        migrations.DeleteModel(
            name='FeedTransaction',
        ),
    ]
