# Generated by Django 5.1.1 on 2025-03-31 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_feed_unique_together_alter_feed_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('name', 'owner')},
        ),
    ]
