# Generated by Django 5.1.1 on 2025-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_feed_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
