# Generated by Django 5.1.1 on 2025-11-07 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_farm_google_sheet_url'),
        ('feed', '0008_feedingplan_feedingplanitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store name (e.g., Main Store, Feed Shed)', max_length=100)),
                ('location_description', models.CharField(blank=True, help_text="Description of the store's location within the farm", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(help_text='The farm this store belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='farms.farm')),
            ],
            options={
                'unique_together': {('name', 'farm')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feed',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store where this feed is kept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feed.store'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('name', 'owner', 'store')},
        ),
    ]
