# Generated by Django 5.1.1 on 2025-11-12 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_store_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('name', 'store')},
        ),
        migrations.AddField(
            model_name='feed',
            name='last_topped_up_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_topped_up_by',
            field=models.ForeignKey(blank=True, help_text='Last user who topped up this feed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topped_up_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created the feed record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
