# Generated by Django 5.1.1 on 2025-11-12 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_feed_unique_together_feed_last_topped_up_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedingplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedingplanitem',
            options={'ordering': ['feed__name']},
        ),
        migrations.AlterUniqueTogether(
            name='feedingplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this feeding plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_plans_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this feeding plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='feed.store'),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='owner',
            field=models.ForeignKey(help_text='User who created this feeding plan', on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedingplanitem',
            name='feed',
            field=models.ForeignKey(help_text='Feed used in this plan', on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plan_items', to='feed.feed'),
        ),
        migrations.AlterUniqueTogether(
            name='feedingplan',
            unique_together={('store', 'name')},
        ),
    ]
