# Generated by Django 5.1.1 on 2025-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees (e.g., 40.7128)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees (e.g., -74.0060)', max_digits=9, null=True),
        ),
    ]
