# Generated by Django 5.1.1 on 2025-03-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_latitude_farm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='vet',
            field=models.ManyToManyField(blank=True, related_name='vet_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FarmVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_staff', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vet_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('farm', 'user')},
            },
        ),
    ]
