# Generated by Django 5.1.1 on 2025-03-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_vet_farmvet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='vet',
        ),
    ]
