# Generated by Django 5.1.1 on 2025-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_remove_farm_staff_remove_farm_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='type',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Sheep', 'Sheep'), ('Crop', 'Crop')], default='Dairy', help_text='Type of farm (Dairy, Sheep, Crop)', max_length=20),
        ),
    ]
