# Generated by Django 5.1.1 on 2025-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the farm', null=True, upload_to='farms/'),
        ),
    ]
