# Generated by Django 5.1.1 on 2025-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_farm_created_at_farm_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='google_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
