# Generated by Django 5.1.1 on 2025-11-14 07:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_farm_google_sheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farms/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='type',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Sheep', 'Sheep'), ('Crop', 'Crop')], default='Dairy', max_length=20),
        ),
    ]
