# Generated by Django 5.1.1 on 2025-11-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug_store', '0002_drug_image'),
        ('feed_store', '0002_feedorder_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug_store.drugorder')),
                ('feed_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed_store.feedorder')),
                ('unified_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.unifiedorder')),
            ],
        ),
    ]
