# Generated by Django 5.1.1 on 2024-12-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_farmer_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('checkup', 'Checkup')], default='consultation', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('unassigned', 'Unassigned')], default='pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vet_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_requests', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.vet')),
            ],
        ),
    ]
