# Generated by Django 5.1.2 on 2024-11-05 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_remove_farmer_role_remove_vet_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('unassigned', 'Unassigned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(default='Jerry', on_delete=django.db.models.deletion.CASCADE, to='profiles.farmer')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.vet')),
            ],
        ),
    ]
