# Generated by Django 5.1.1 on 2024-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetrequest',
            name='service_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
